name: CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  # ======= Backend and Frontend Tests =======
  backend-tests:
    name: Backend Tests (Spring Boot App)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout version
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "maven"

      - name: Run Unit Tests
        run: mvn clean test
        working-directory: back

      - name: Run Integration Tests
        run: mvn verify -P integration-tests
        working-directory: back

      - name: Generate test coverage report
        run: mvn jacoco:report
        working-directory: back

      - name: Upload backend coverage artifact (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-html
          path: back/target/site/jacoco

      - name: Upload backend coverage artifact (XML)
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-xml
          path: back/target/site/jacoco/jacoco.xml

  frontend-tests:
    name: Frontend Tests (Angular App)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: "front/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: front

      - name: Run unit tests
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
        working-directory: front

  # ======= Dockerize Jobs =======
  deploy_backend:
    name: Deploy Backend (Spring Boot App)
    runs-on: ubuntu-latest
    needs: backend-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout version
        uses: actions/checkout@v4

      - name: Set up JDK 11 for Backend Build
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "maven"

      - name: Build Spring Boot Application
        run: mvn clean package -DskipTests
        working-directory: back

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: swymn/openclassrooms-p10
          tags: |
            type=sha,format=short,prefix=backend-
            type=raw,value=backend-latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          flavor: |
            latest=false

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: back
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=swymn/openclassrooms-p10:buildcache
          cache-to: type=registry,ref=swymn/openclassrooms-p10:buildcache,mode=max

  deploy_frontend:
    name: Deploy Frontend (Angular App)
    runs-on: ubuntu-latest
    needs: frontend-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: "front/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: front

      - name: Build Angular Application
        run: npm run build
        working-directory: front

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: swymn/openclassrooms-p10
          tags: |
            type=sha,format=short,prefix=frontend-
            type=raw,value=frontend-latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          flavor: |
            latest=false

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: back
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=swymn/openclassrooms-p10:buildcache
          cache-to: type=registry,ref=swymn/openclassrooms-p10:buildcache,mode=max

  # ======= Quality Gate =======
  sonarqube_scan_frontend:
    name: SonarQube Scan Frontend
    runs-on: ubuntu-latest
    needs: frontend-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          projectBaseDir: front
          args: >
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.projectKey=swymn_venture-ugo-p10-frontend
            -Dsonar.organization=swymn
            -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
        
  sonarqube_scan_backend:
    name: SonarQube Scan Backend
    runs-on: ubuntu-latest
    needs: backend-tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.branch.name=${{ github.ref_name }} -Dsonar.organization=swymn -Dsonar.projectKey=swymn_venture-ugo-p10-backend
        working-directory: back
